"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format="$directory$jobs$character"
right_format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$battery\
$time\
$status\
$os\
$container\
$shell\
"""




[line_break]
disabled = true

[python]
disabled=false
symbol=''
format = '[${symbol}( \($virtualenv\) )]($style)'

[perl]
disabled=true

[c]
disabled=true

[character] 
success_symbol = "[➜](bold cyan)" 
error_symbol ="[➜](bold cyan)"

[jobs]
disabled = true

[package]
disabled = true

[sudo]
style = "bold blue"
format = "[$symbol]($style)"
symbol = " "
disabled = false

[directory]
read_only = "."
read_only_style = "bold blue"
style = "bold blue"

#TODO: SKONCZYC TE GLUPIE SSH
[hostname]
ssh_only = true
ssh_symbol = ""
style = "bold yellow"
format = "[$ssh_symbol$hostname]($style) in "
disabled = false

[cmd_duration]
style = "bold yellow"
disabled = false
format = "took [$duration]($style) "


[battery]
disabled = true
